### ISSUE TITLE
Add options to hide next/back buttons

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/vscode-wizard#12]
Some form pages or single-page wizard  might only want an ok / finish type button, no next/back at all.

**Comment by angelozerr** [comment]
In vscode-kafka I would like to remove all button and add a Save icon on the right top of the form page.

In otherwise instead of having this UI:

![image](https://user-images.githubusercontent.com/1932211/119225630-1797ff80-bb05-11eb-87d5-8291b20eee96.png)


I would like to have this UI (with a save icon):

![image](https://user-images.githubusercontent.com/1932211/119225607-ea4b5180-bb04-11eb-8673-5b6f2e24fe5c.png)

@fbricon what do you think about this idea?

**Comment by fbricon** [comment]
save icon on top right looks out of place IMO.
However, 
- hiding the prev/next buttons make sense when there are no other pages
- being able to rename the finish button (to save) would be nice
