### ISSUE TITLE
First class support for lists, with various data types supported

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/vscode-wizard#14]
Some clients (vscode-kafka) may wish to present a list of items / files / string values. They may wish to have add / remove buttons with different logic based on datatype (text box input vs file-chooser).  Some may also wish to have reorder abilities to move items up or down in the list.

**Comment by angelozerr** [comment]
@robstryker this issue is not required for vscode-kafka, because we decide to use a simple input type to manage our certificate files.But we need an UI input with a browse file button. In other words, we need this issue https://github.com/redhat-developer/vscode-wizard/issues/34.

I think I can manage that with a custom renderer, but if vscode-wizard provides this feature as default, it should be nicer.

**Comment by robstryker** [comment]
issue #34 was closed as fixed.
