### ISSUE TITLE
How to manage property fields (disabled,checked, etc) according value of another field?

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-wizard#59]
In vscode-kafka we have several usecases where UI property field (checked, disable)  depends on an another UI property field.

# disable html inputs according to a value of select

When None Mechanism is selected, the Username, Password should be disabled:

![image](https://user-images.githubusercontent.com/1932211/124284368-38646380-db4d-11eb-80cd-9f5a10d6866b.png)

# check a checkbox when another checkbox is selected

When a Mechanism is selected, the SSL checbox must be checked automaticly

![image](https://user-images.githubusercontent.com/1932211/124286040-d1e04500-db4e-11eb-94dc-7a69c359072d.png)

**Comment by robstryker** [comment]
Override the renderer and customize the   isFieldEnabled(oneField: WizardPageFieldDefinition, data: any): boolean function?

I haven't tried it but it could work? I put the function there to be overridden.

**Comment by robstryker** [comment]
So... it turns out that overriding the renderer isn't enough itself, because the renderer won't naturally rewrite widgets. It doesn't need to. It only writes them once and then writes to the validation fields. 

I've expanded that, so now validators can also return a list of widgets that need to be redrawn from values in the data map.   Will work on committing it.
