### ISSUE TITLE
Is it possible to create a readonly field?

### ISSUE THREAD

**Issue by k-jay-c** [redhat-developer/vscode-wizard#70]
Hi,

Is it possible to create a field (text box or other types) and set it to readonly but have the initial value passed in when creating the wizard?

**Comment by robstryker** [comment]
It is possible, but I'm cleaning up the functionality a bit to make it nicer. Maybe next week it'll be released with more clear examples?  Will do my best here! This is a primary use case of one of our users.

**Comment by k-jay-c** [comment]
Thank you for the quick response.  Look forward to the update.

**Comment by robstryker** [comment]
In current code, easiest is the following:
```
                {
                    id: "awesome",
                    label: "Are you awesome??",
                    type: "checkbox",
                    description: "Are you awesome?",
                    initialValue: "true",
                    properties: {
                        disabled: true
                    }
```

But we're trying to clean that up because the presence of the `any` type properties is just kinda ugly and not helpful to the extender. For now, this should work for you though.

**Comment by robstryker** [comment]
Also we're trying to fix the way it maintains that state so it's easier to start a field off as disabled but transition it to enabled under some condition or validation event.

**Comment by k-jay-c** [comment]
> Also we're trying to fix the way it maintains that state so it's easier to start a field off as disabled but transition it to enabled under some condition or validation event.

Exactly what I'm looking to do!  Will use the above in the meanwhile.  Thank you.

**Comment by robstryker** [comment]
https://github.com/robstryker/vscode-wizard-example-extension has a new sample, but making it work is a bit iffy. 

Since the state map is actually almost entirely stored in the webview, but it does pass it in one direction to the extension, changes in enablement can be done in your validator, but changes to actual values in the map must be done in the webview. So we've added a few things.

1) The validator response can now include field visibility and enablement in the return items. The renderer will make sure to update via templates any divs that that affects, and...
2) if you actually need clicking on something to change the values of another widget, you will need to pass in the intentionally-long-named `executableJavascriptOnModification` property on your field definition, where you can overwrite the onModify or onChange events. 

It's not ideal, but, it'll work for now. Eventually I might be able to change the protocol enough in a backwards compatibile way that each event actually returns the map's new state with it so the extension itself can modify it. But for now that's a bit more work than I had time for and a bit riskier since it involves changing the way the two layers communicate. 

Let me know if this works for you!

**Comment by k-jay-c** [comment]
Thanks @robstryker  - it has worked.  Running into a few other issues so will open separate issues for them.
